[build-system]
requires = ["maturin<=1.3.1"]
build-backend = "maturin"

[project]
name = "tantivy"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "nox",
]

[tool.maturin]
bindings = "pyo3"
